### ISSUE TITLE
Pip install throws an error

### ISSUE THREAD

**Issue by swaathi** [HeyImAlex/rratelimit#2]
I'm trying to `pip install`, but it keeps throwing an error. I ended up installing from source instead.

```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 179, in main
    for name in ["pip._vendor", "distlib", "requests", "urllib3"]
  File "/usr/local/lib/python2.7/site-packages/pip/compat/dictconfig.py", line 565, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python2.7/site-packages/pip/compat/dictconfig.py", line 332, in configure
    del logging._handlerList[:]
AttributeError: 'module' object has no attribute '_handlerList'
```

**Comment by heyimalex** [comment]
I wasn't able to recreate the error, but I did find [this](https://github.com/pypa/pip/issues/3193) similar issue? I suspect something similar is happening, since the error is coming from inside of pip.

**Comment by swaathi** [comment]
Yes! I think you're right. Closing this. :)

**Comment by mecampbellsoup** [comment]
@swaathi did you figure this one out? Hitting the same issue..
